language: php

php:
  - 5.3.3
  - 5.4
  - 5.5

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
    - sh -c 'echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
    - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -ge 5 ]; then echo "zend_extension = opcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -le 3 ]; then echo "short_open_tag = On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - ( cd tests; mkdir data; ../vendor/bin/doctrine orm:schema-tool:create )

script: 
    - phpunit -v -c tests
